import type { Interactable, Soul, SoulId } from "./types";

export const soulData: Record<SoulId, Soul> = {
  onde: {
    id: "onde",
    name: "Onde (Wave)",
    role: "Control / Displacement",
    baseStats: { hp: 80, pa: 4, pm: 3, mana: 5 },
    baseAttack: {
      id: "water_bolt",
      name: "Water Bolt",
      paCost: 2,
      pmCost: 0,
      manaCost: 0,
      range: 3,
      damage: 15,
      type: "attack",
      desc: "Basic ranged attack.",
      initiative: 50,
      maxUsesPerTurn: 2,
    },
    ultimate: {
      id: "resonance",
      name: "Résonance (Ult)",
      paCost: 0,
      pmCost: 0,
      manaCost: 3,
      range: 5,
      damage: 40,
      type: "attack",
      desc: "High damage based on movement.",
      initiative: 20,
      cooldown: 3,
    },
    actives: [
      {
        id: "impulse",
        name: "Impulsion",
        paCost: 2,
        pmCost: 0,
        manaCost: 0,
        range: 2,
        damage: 15,
        type: "attack",
        desc: "Repels target 1 cell.",
        initiative: 60,
        cooldown: 1,
      },
      {
        id: "stasis",
        name: "Zone de Stase",
        paCost: 1,
        pmCost: 0,
        manaCost: 2,
        range: 3,
        damage: 0,
        type: "attack",
        desc: "Stuns the target for 1 turn.",
        initiative: 70,
        cooldown: 2,
        effect: {
          id: "stasis_stun",
          type: "stun",
          name: "Stasis",
          duration: 1,
        },
      },
      {
        id: "flux",
        name: "Rivière de Flux",
        paCost: 2,
        pmCost: 0,
        manaCost: 1,
        range: 4,
        damage: 10,
        type: "attack",
        desc: "Damages in a line.",
        initiative: 40,
        maxUsesPerTurn: 1,
      },
    ],
    passives: [
      {
        id: "drain_force",
        name: "Drain de Force",
        desc: "Gain 1 Mana when displacing an enemy.",
        effect: "drain_force",
      },
      {
        id: "flow_state",
        name: "Flow State",
        desc: "If you do not move, next spell gains +1 Range.",
        effect: "flow_state",
      },
    ],
  },
  fury: {
    id: "fury",
    name: "Fury (Berserk)",
    role: "Melee / Burst",
    baseStats: { hp: 120, pa: 3, pm: 4, mana: 3 },
    baseAttack: {
      id: "slash",
      name: "Rending Slash",
      paCost: 2,
      pmCost: 0,
      manaCost: 0,
      range: 1,
      damage: 25,
      type: "attack",
      desc: "High damage melee attack. Applies Bleed.",
      initiative: 50,
      maxUsesPerTurn: 2,
      effect: {
        id: "bleed",
        type: "dot",
        name: "Bleed",
        duration: 2,
        value: 10,
      },
    },
    ultimate: {
      id: "execute",
      name: "Guillotine (Ult)",
      paCost: 3,
      pmCost: 0,
      manaCost: 2,
      range: 1,
      damage: 50,
      type: "attack",
      desc: "Massive execution damage.",
      initiative: 30,
      cooldown: 3,
    },
    actives: [
      {
        id: "leap",
        name: "Savage Leap",
        paCost: 1,
        pmCost: 0,
        manaCost: 1,
        range: 3,
        damage: 15,
        type: "move_attack",
        desc: "Jump to cell and damage adjacent.",
        initiative: 80,
        cooldown: 2,
      },
      {
        id: "bloodlust",
        name: "Bloodlust",
        paCost: 1,
        pmCost: 0,
        manaCost: 2,
        range: 0,
        damage: 0,
        type: "buff",
        desc: "Increases damage of next attack.",
        initiative: 90,
        cooldown: 2,
      },
      {
        id: "whirlwind",
        name: "Whirlwind",
        paCost: 2,
        pmCost: 0,
        manaCost: 1,
        range: 1,
        damage: 20,
        type: "attack",
        desc: "AoE damage around self.",
        initiative: 45,
        maxUsesPerTurn: 1,
      },
    ],
    passives: [
      {
        id: "masochism",
        name: "Masochism",
        desc: "Taking damage restores 1 PA for the next turn.",
        effect: "masochism",
      },
      {
        id: "momentum",
        name: "Momentum",
        desc: "Each cell moved increases next attack damage by 2.",
        effect: "momentum",
      },
    ],
  },
  aegis: {
    id: "aegis",
    name: "Aegis (Fortress)",
    role: "Defense / Zone",
    baseStats: { hp: 150, pa: 3, pm: 2, mana: 4 },
    baseAttack: {
      id: "shield_bash",
      name: "Shield Bash",
      paCost: 2,
      pmCost: 0,
      manaCost: 0,
      range: 1,
      damage: 15,
      type: "attack",
      desc: "Damages target.",
      initiative: 50,
      maxUsesPerTurn: 2,
    },
    ultimate: {
      id: "bastion",
      name: "Iron Maiden (Ult)",
      paCost: 0,
      pmCost: 0,
      manaCost: 4,
      range: 2,
      damage: 30,
      type: "attack",
      desc: "Reflects damage taken previously.",
      initiative: 10,
      cooldown: 3,
    },
    actives: [
      {
        id: "phalanx",
        name: "Phalanx Wall",
        paCost: 1,
        pmCost: 0,
        manaCost: 2,
        range: 3,
        damage: 0,
        type: "trap",
        desc: "Creates impassable terrain.",
        initiative: 70,
        cooldown: 2,
      },
      {
        id: "taunt",
        name: "Magnetic Pull",
        paCost: 1,
        pmCost: 0,
        manaCost: 1,
        range: 4,
        damage: 0,
        type: "control",
        desc: "Pulls target closer.",
        initiative: 60,
        cooldown: 1,
      },
      {
        id: "fortify",
        name: "Fortify",
        paCost: 2,
        pmCost: 0,
        manaCost: 0,
        range: 0,
        damage: 0,
        type: "buff",
        desc: "Grants 30 HP shield for 2 turns.",
        initiative: 95,
        cooldown: 3,
        effect: {
          id: "fortify_shield",
          type: "shield",
          name: "Fortified",
          duration: 2,
          value: 30,
        },
      },
    ],
    passives: [
      {
        id: "thorns",
        name: "Thorns",
        desc: "Enemies attacking from range 1 take 5 damage.",
        effect: "thorns",
      },
      {
        id: "heavy_plating",
        name: "Heavy Plating",
        desc: "Max PM reduced by 1, reduce all incoming damage by 3.",
        effect: "heavy_plating",
      },
    ],
  },
  umbra: {
    id: "umbra",
    name: "Umbra (Shadow)",
    role: "Assassin / Mobility",
    baseStats: { hp: 70, pa: 4, pm: 4, mana: 4 },
    baseAttack: {
      id: "shadow_strike",
      name: "Shadow Strike",
      paCost: 2,
      pmCost: 0,
      manaCost: 0,
      range: 1,
      damage: 20,
      type: "attack",
      desc: "Quick melee strike.",
      initiative: 70,
      maxUsesPerTurn: 2,
    },
    ultimate: {
      id: "assassinate",
      name: "Assassinate (Ult)",
      paCost: 0,
      pmCost: 0,
      manaCost: 4,
      range: 1,
      damage: 60,
      type: "attack",
      desc: "Massive damage to a single target.",
      initiative: 90,
      cooldown: 3,
    },
    actives: [
      {
        id: "blink",
        name: "Blink",
        paCost: 1,
        pmCost: 0,
        manaCost: 1,
        range: 3,
        damage: 0,
        type: "control", // Using control for teleport for now
        desc: "Teleport to a target cell.",
        initiative: 85,
        cooldown: 2,
      },
      {
        id: "vanish",
        name: "Vanish",
        paCost: 2,
        pmCost: 0,
        manaCost: 1,
        range: 0,
        damage: 0,
        type: "buff",
        desc: "Become stealthed for 1 turn.",
        initiative: 95,
        cooldown: 3,
        effect: {
          id: "stealth_effect",
          type: "stealth",
          name: "Stealthed",
          duration: 1,
        },
      },
      {
        id: "shadow_bolt",
        name: "Shadow Bolt",
        paCost: 2,
        pmCost: 0,
        manaCost: 1,
        range: 4,
        damage: 15,
        type: "attack",
        desc: "Ranged shadow attack.",
        initiative: 40,
        maxUsesPerTurn: 1,
      },
    ],
    passives: [
      {
        id: "opportunist",
        name: "Opportunist",
        desc: "Deal 5 extra damage if target is below 50% HP.",
        effect: "opportunist",
      },
      {
        id: "shadow_step",
        name: "Shadow Step",
        desc: "After an ability, next move costs 0 PM.",
        effect: "shadow_step",
      },
    ],
  },
  verdant: {
    id: "verdant",
    name: "Verdant (Nature)",
    role: "Control / Sustain",
    baseStats: { hp: 100, pa: 3, pm: 3, mana: 6 },
    baseAttack: {
      id: "vine_whip",
      name: "Vine Whip",
      paCost: 2,
      pmCost: 0,
      manaCost: 0,
      range: 2,
      damage: 15,
      type: "attack",
      desc: "Mid-range whip attack.",
      initiative: 50,
      maxUsesPerTurn: 2,
    },
    ultimate: {
      id: "wrath_of_nature",
      name: "Wrath of Nature (Ult)",
      paCost: 0,
      pmCost: 0,
      manaCost: 4,
      range: 3,
      damage: 35,
      type: "attack",
      desc: "AoE damage and roots all hit enemies.",
      initiative: 30,
      cooldown: 3,
      effect: {
        id: "wrath_root",
        type: "root",
        name: "Rooted",
        duration: 1,
      },
    },
    actives: [
      {
        id: "entangle",
        name: "Entangle",
        paCost: 2,
        pmCost: 0,
        manaCost: 1,
        range: 3,
        damage: 10,
        type: "control",
        desc: "Damages and roots the target.",
        initiative: 45,
        cooldown: 2,
        effect: {
          id: "entangle_root",
          type: "root",
          name: "Rooted",
          duration: 1,
        },
      },
      {
        id: "brier_wall",
        name: "Brier Wall",
        paCost: 1,
        pmCost: 0,
        manaCost: 2,
        range: 3,
        damage: 0,
        type: "trap",
        desc: "Creates a wall of thorns.",
        initiative: 60,
        cooldown: 2,
      },
      {
        id: "bloom",
        name: "Healing Bloom",
        paCost: 2,
        pmCost: 0,
        manaCost: 2,
        range: 0,
        damage: 0,
        type: "buff",
        desc: "Heals self for 20 HP.",
        initiative: 80,
        cooldown: 2,
      },
    ],
    passives: [
      {
        id: "root_system",
        name: "Root System",
        desc: "If you do not move, heal 5 HP at the end of the turn.",
        effect: "root_system",
      },
    ],
  },
  volt: {
    id: "volt",
    name: "Volt (Spark)",
    role: "Mobility / Chain",
    baseStats: { hp: 90, pa: 5, pm: 4, mana: 4 },
    baseAttack: {
      id: "spark",
      name: "Spark",
      paCost: 2,
      pmCost: 0,
      manaCost: 0,
      range: 3,
      damage: 12,
      type: "attack",
      desc: "Quick electrical discharge.",
      initiative: 60,
      maxUsesPerTurn: 2,
    },
    ultimate: {
      id: "overload",
      name: "Overload (Ult)",
      paCost: 0,
      pmCost: 0,
      manaCost: 3,
      range: 0,
      damage: 0,
      type: "buff",
      desc: "Gain +2 PA and +2 PM for the next turn.",
      initiative: 95,
      cooldown: 4,
    },
    actives: [
      {
        id: "chain_lightning",
        name: "Chain Lightning",
        paCost: 3,
        pmCost: 0,
        manaCost: 2,
        range: 4,
        damage: 20,
        type: "attack",
        desc: "Powerful strike that chains to nearby enemies.",
        initiative: 40,
        cooldown: 2,
      },
      {
        id: "thunder_dash",
        name: "Thunder Dash",
        paCost: 1,
        pmCost: 0,
        manaCost: 1,
        range: 3,
        damage: 10,
        type: "move_attack",
        desc: "Dash to cell, damaging those passed through.",
        initiative: 85,
        cooldown: 1,
      },
      {
        id: "static_field",
        name: "Static Field",
        paCost: 2,
        pmCost: 0,
        manaCost: 1,
        range: 2,
        damage: 5,
        type: "control",
        desc: "Deals low damage and reduces target's PM by 2.",
        initiative: 55,
        cooldown: 2,
      },
    ],
    passives: [
      {
        id: "supercharged",
        name: "Supercharged",
        desc: "Gain 1 PM when spending 2 or more Mana in a turn.",
        effect: "supercharged",
      },
      {
        id: "conductivity",
        name: "Conductivity",
        desc: "Attacks against targets standing on Mana Wells deal +5 damage.",
        effect: "conductivity",
      },
    ],
  },
};

// Static obstacles for practice arena
export const obstacles: Array<{ x: number; y: number }> = [
  { x: 5, y: 4 },
  { x: 5, y: 5 },
  { x: 5, y: 6 },
  { x: 5, y: 7 },
  { x: 10, y: 8 },
  { x: 10, y: 9 },
  { x: 10, y: 10 },
  { x: 10, y: 11 },
  { x: 8, y: 2 },
  { x: 9, y: 2 },
  { x: 8, y: 13 },
  { x: 9, y: 13 },
];

// Initial interactables for the arena (mana wells)
export const initialInteractables: Array<Interactable> = [
  {
    id: "well_1",
    type: "mana_well",
    pos: { x: 3, y: 8 },
    duration: -1,
    value: 2,
    triggeredBy: "player",
  },
  {
    id: "well_2",
    type: "mana_well",
    pos: { x: 12, y: 8 },
    duration: -1,
    value: 2,
    triggeredBy: "enemy",
  },
  {
    id: "well_3",
    type: "mana_well",
    pos: { x: 7, y: 7 },
    duration: -1,
    value: 1,
    triggeredBy: "both",
  },
  {
    id: "hp_pack_1",
    type: "hp_pack",
    pos: { x: 5, y: 3 },
    duration: -1,
    value: 20,
    triggeredBy: "both",
  },
  {
    id: "hp_pack_2",
    type: "hp_pack",
    pos: { x: 10, y: 12 },
    duration: -1,
    value: 20,
    triggeredBy: "both",
  },
  {
    id: "mana_pack_1",
    type: "mana_pack",
    pos: { x: 2, y: 13 },
    duration: -1,
    value: 2,
    triggeredBy: "both",
  },
  {
    id: "mana_pack_2",
    type: "mana_pack",
    pos: { x: 13, y: 2 },
    duration: -1,
    value: 2,
    triggeredBy: "both",
  },
  {
    id: "pa_boost_1",
    type: "pa_boost",
    pos: { x: 1, y: 1 },
    duration: -1,
    value: 1,
    triggeredBy: "both",
  },
  {
    id: "pm_boost_1",
    type: "pm_boost",
    pos: { x: 14, y: 14 },
    duration: -1,
    value: 1,
    triggeredBy: "both",
  },
];
